package com.example.staticmethods;

import static org.junit.Assert.assertEquals;
import org.junit.Test;


// Test generated by Diffblue before merge of PR 4890.
// Generated using Diffblue Cover 2021.06.01-SNAPSHOT-b78406f
// No test generated after the merge.
// SO THIS IS THE TEST WE'VE LOST - it seems crucial that it's an enum.
public class CurrencyBeforeMergeDiffblueTest {
  @Test
  public void testGetBase() {
    // Arrange, Act and Assert
    assertEquals(Currency.USD, Currency.getBase());
  }
}

