package com.example.staticmethods;

import static org.junit.Assert.assertEquals;
import org.junit.Test;

// Test generated by Diffblue before merge of PR 4890.
// Diffblue Cover 2021.06.01-SNAPSHOT-b78406f
// But this test is not lost.
public class StaticNonTrivialMethodsDiffblueTest {
  @Test
  public void testGetBase() {
    // Arrange, Act and Assert
    assertEquals("hello", StaticNonTrivialMethods.getBase());
  }
}

